<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="CityAdmin.aspx.cs" Inherits="RealEstateMarket.Admin.Dashboard.CityAdmin" %>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
	<h4>
		Cập nhật thông tin các thành phố
	</h4>
	<asp:ObjectDataSource ID="dataSource" runat="server" 
	DeleteMethod="DeleteCity" 
	InsertMethod="InsertCity" 
	SelectMethod="GetAllCities"
	TypeName="RealEstateMarket.RealEstateServiceReference.RealEstateWebServiceSoapClient" 
	UpdateMethod="UpdateCity">
		<DeleteParameters>
			<asp:Parameter Name="id" Type="Int32" />
		</DeleteParameters>
		<InsertParameters>
			<asp:Parameter Name="name" Type="String" />
			<asp:Parameter Name="nationID" Type="Int32" />
		</InsertParameters>
		<UpdateParameters>
			<asp:Parameter Name="id" Type="Int32" />
			<asp:Parameter Name="name" Type="String" />
			<asp:Parameter Name="nationID" Type="Int32" />
		</UpdateParameters>
	</asp:ObjectDataSource>
	
	<asp:ObjectDataSource ID="dataSourceNation" runat="server" 
	SelectMethod="GetAllNations"        
		TypeName="RealEstateMarket.RealEstateServiceReference.RealEstateWebServiceSoapClient">
	</asp:ObjectDataSource>

	<asp:Table runat="server">
		<asp:TableRow>
			<asp:TableCell>
				<asp:GridView 
					runat="server" 
					ID="dataTable"
					DataSourceID="dataSource"
					DataKeyNames="ID"
					AllowPaging="True" 
					AutoGenerateDeleteButton="True"
					AutoGenerateEditButton="True" 
					BackColor="White" BorderColor="#336666" 
					BorderStyle="Double" BorderWidth="3px" CellPadding="4" 
					GridLines="Horizontal" AutoGenerateColumns="False">
						<Columns>
							<asp:TemplateField HeaderText="STT">
							<ItemTemplate>
								<%# Container.DataItemIndex + 1 %>
							</ItemTemplate>
						</asp:TemplateField>
							<asp:BoundField DataField="Name" HeaderText="Tên thành phố" ControlStyle-Width="300px"/>
							<asp:TemplateField HeaderText="Quốc gia">
								<EditItemTemplate>
									<asp:DropDownList ID="DropDownList1" runat="server"
										DataSourceID="dataSourceNation"
										DataTextField="Name"
										DataValueField="ID"
										SelectedValue='<%# Bind("NationID") %>'>
									</asp:DropDownList>
								</EditItemTemplate>
								<ItemTemplate>
								   <asp:DropDownList ID="DropDownList2" runat="server"
										DataSourceID="dataSourceNation"
										DataTextField="Name"
										DataValueField="ID"
										SelectedValue='<%# Bind("NationID") %>'
										Enabled="false">
									</asp:DropDownList>
							   </ItemTemplate>
							</asp:TemplateField>                            
							<asp:BoundField DataField="ID" HeaderText="ID" ReadOnly="True" 
								SortExpression="ID" />
					</Columns>
						<FooterStyle BackColor="White" ForeColor="#333333" />
					<HeaderStyle BackColor="#336666" Font-Bold="True" ForeColor="White" />
					<PagerStyle BackColor="#336666" ForeColor="White" HorizontalAlign="Center" />
						<RowStyle ForeColor="#333333" BackColor="White"></RowStyle>
					<SortedAscendingCellStyle BackColor="#F7F7F7" />
					<SortedAscendingHeaderStyle BackColor="#487575" />
					<SortedDescendingCellStyle BackColor="#E5E5E5" />
					<SortedDescendingHeaderStyle BackColor="#275353" />
				</asp:GridView>
			</asp:TableCell>
			<asp:TableCell>
				<asp:Label ID="lblName" runat="server" Text="City's name:"></asp:Label>
				<asp:TextBox ID="textboxName" runat="server"></asp:TextBox>
				<br/>
				<asp:Label ID="lblNationID" runat="server" Text="Nation:"></asp:Label>
				<asp:DropDownList ID="ddlNation" runat="server" DataSourceID="dataSourceNation"
					DataTextField="Name"
					DataValueField="ID">
				</asp:DropDownList>
				<br />
				<asp:Button ID="Insert" runat="server" Text="Insert" onclick="Insert_Click" />
				<asp:Label ID="error" runat="server" Text="Label"></asp:Label>
			</asp:TableCell>
		</asp:TableRow>
	</asp:Table>
	
</asp:Content>
