<%@ Page Title="" Language="C#" MasterPageFile="~/Master/Admin.Master" AutoEventWireup="true" CodeBehind="CityAdmin.aspx.cs" Inherits="RealEstateMarket.Admin.Dashboard.CityAdmin" %>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
	<asp:ObjectDataSource ID="CityObjectDataSource" runat="server" 
	DeleteMethod="DeleteCity" 
	InsertMethod="InsertCity" 
	SelectMethod="GetAllCities"
	TypeName="RealEstateMarket.RealEstateServiceReference.RealEstateWebServiceSoapClient" 
	UpdateMethod="UpdateCity">
		<DeleteParameters>
			<asp:Parameter Name="id" Type="Int32" />
		</DeleteParameters>
		<InsertParameters>
			<asp:Parameter Name="name" Type="String" />
			<asp:Parameter Name="nationID" Type="Int32" />
		</InsertParameters>
		<UpdateParameters>
			<asp:Parameter Name="id" Type="Int32" />
			<asp:Parameter Name="name" Type="String" />
			<asp:Parameter Name="nationID" Type="Int32" />
		</UpdateParameters>
	</asp:ObjectDataSource>
	
	<asp:ObjectDataSource ID="NationDataSource" runat="server" 
	SelectMethod="GetAllNations"        
		TypeName="RealEstateMarket.RealEstateServiceReference.RealEstateWebServiceSoapClient">
	</asp:ObjectDataSource>
    
	<asp:Table runat="server">
		<asp:TableRow>
			<asp:TableCell>
				<asp:GridView 
					runat="server" 
					ID="CityGridView"
					DataSourceID="CityObjectDataSource"
					DataKeyNames="ID"
					AllowPaging="True" 
					AutoGenerateDeleteButton="True"
					AutoGenerateEditButton="True" AutoGenerateColumns="False">
						<Columns>
							<asp:TemplateField HeaderText="STT">
							<ItemTemplate>
								<%# Container.DataItemIndex + 1 %>
							</ItemTemplate>
						</asp:TemplateField>
							<asp:BoundField DataField="Name" HeaderText="Tên thành phố" 
                                ControlStyle-Width="300px"><ControlStyle Width="300px"></ControlStyle>
                            </asp:BoundField>
							<asp:TemplateField HeaderText="Quốc gia">
								<EditItemTemplate>
									<asp:DropDownList ID="EditDropDownList" runat="server"
										DataSourceID="NationDataSource"
										DataTextField="Name"
										DataValueField="ID"
										SelectedValue='<%# Bind("NationID") %>'>
									</asp:DropDownList>
								</EditItemTemplate>
								<ItemTemplate>
                                    <%# RealEstateMarket._Default.db.GetNation(Convert.ToInt32(Eval("NationID"))).Name %>
							   </ItemTemplate>
							</asp:TemplateField>                            
							<asp:BoundField DataField="ID" HeaderText="ID" ReadOnly="True" 
								SortExpression="ID" />
					</Columns>
				</asp:GridView>
			</asp:TableCell>
			<asp:TableCell>
                <table>
                    <tr>
                        <td colspan="2">
                            <asp:ValidationSummary ID="ValidationSummary" runat="server" ValidationGroup="InsertCityValidationGroup"
                                CssClass="failureNotification"
                                HeaderText="Bạn phải điền vào các phần còn thiếu" /><br />
                            <asp:Label ID="ErrorLabel" runat="server" Text="" CssClass="failureNotification"></asp:Label>
                        </td>                        
                    </tr>
                    <tr>
                        <td>
                            <asp:Label ID="CityNameLabel" runat="server" Text="Tên Thành phố:" 
                                AssociatedControlID="CityNameTextBox"></asp:Label>
                        </td>
                        <td>
                            <asp:TextBox ID="CityNameTextBox" runat="server" ToolTip="Tên Thành Phố"></asp:TextBox>
                            <asp:RequiredFieldValidator ID="CityNameRequiredFieldValidator" runat="server"
                                ControlToValidate="CityNameTextBox" InitialValue=""
                                CssClass="failureNotification" ErrorMessage="Nhập tên Thành Phố"
                                ToolTip="Nhập tên Thành Phố" ValidationGroup="InsertCityValidationGroup">*</asp:RequiredFieldValidator>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <asp:Label ID="NationIDLabel" runat="server" Text="Quốc gia:" 
                                AssociatedControlID="NationDropDownList"></asp:Label>
                        </td>
                        <td>
                            <asp:DropDownList ID="NationDropDownList" runat="server" DataSourceID="NationDataSource"
					            DataTextField="Name"
					            DataValueField="ID">
				            </asp:DropDownList>
                        </td>
                    </tr>
                </table>
				<asp:Button ID="InsertButton" runat="server" Text="Thêm mới" onclick="InsertButton_Click" 
                     ValidationGroup="InsertCityValidationGroup"/>
			</asp:TableCell>
		</asp:TableRow>
	</asp:Table>	
</asp:Content>
