<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="NationAdmin.aspx.cs" Inherits="RealEstateMarket.Admin.Dashboard.NationAdmin" %>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
    <h4>
        Cập nhật thông tin các quốc gia
    </h4>
    <asp:Table runat="server">
        <asp:TableRow>
            <asp:TableCell>
                <asp:GridView 
                    runat="server" 
                    ID="NationGridView"
                    DataSourceID="NationObjectDataSource"
                    DataKeyNames="ID"
                    AllowPaging="True" 
                    AutoGenerateDeleteButton="True"
                    AutoGenerateEditButton="True" BackColor="White" BorderColor="#336666" 
                    BorderStyle="Double" BorderWidth="3px" CellPadding="4" 
                    GridLines="Horizontal" AutoGenerateColumns="False">
                    <SelectedRowStyle ForeColor="White" Font-Bold="True" 
                           BackColor="#339966"></SelectedRowStyle>
                    <Columns>
                        <asp:TemplateField HeaderText="STT">
                            <ItemTemplate>
                                <%# Container.DataItemIndex + 1 %>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:BoundField DataField="Name" HeaderText="Tên Quốc Gia" />
                        <asp:BoundField DataField="NationCode" HeaderText="Mã Quốc Gia" />
                        <asp:BoundField DataField="ID" HeaderText="ID" ReadOnly="True" />
                    </Columns>
                    <FooterStyle BackColor="White" ForeColor="#333333" />
                    <HeaderStyle BackColor="#336666" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#336666" ForeColor="White" HorizontalAlign="Center" />
                    <RowStyle ForeColor="#333333" BackColor="White"></RowStyle>
                    <SortedAscendingCellStyle BackColor="#F7F7F7" />
                    <SortedAscendingHeaderStyle BackColor="#487575" />
                    <SortedDescendingCellStyle BackColor="#E5E5E5" />
                    <SortedDescendingHeaderStyle BackColor="#275353" />
                </asp:GridView>
            </asp:TableCell>
            <asp:TableCell>
                <table>
                    <tr>
                        <td colspan="2">
                            <asp:ValidationSummary ID="InsertNationValidationSummary" runat="server" CssClass="failureNotification"
                                ValidationGroup="InsertNationValidationGroup" HeaderText="Bạn phải điền vào các phần còn thiếu" /><br />
                            <asp:Label ID="ErrorLabel" runat="server" Text="" CssClass="failureNotification"></asp:Label>
                        </td>                        
                    </tr>
                    <tr>
                        <td>
                            <asp:Label ID="NationNameLabel" runat="server" Text="Nation's name:"
                                AssociatedControlID="NationNameTextBox"></asp:Label>
                        </td>
                        <td>
                            <asp:TextBox ID="NationNameTextBox" runat="server" ToolTip="Nhập Tên Quốc Gia"
                                CssClass="textEntry"></asp:TextBox>
                            <asp:RequiredFieldValidator ID="NationNameTextBoxRequiredFieldValidator" runat="server"
                                ControlToValidate="NationNameTextBox" InitialValue=""
                                CssClass="failureNotification" ErrorMessage="Bạn chưa nhập Tên Quốc Gia"
                                ValidationGroup="InsertNationValidationGroup">*</asp:RequiredFieldValidator>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <asp:Label ID="NationCodeLabel" runat="server" Text="Nation Code:"
                                AssociatedControlID="NationCodeTextBox"></asp:Label>
                        </td>
                        <td>
                            <asp:TextBox ID="NationCodeTextBox" runat="server" ToolTip="Nhập Mã Quốc gia"
                                CssClass="textEntry"></asp:TextBox>
                        </td>
                    </tr>
                </table>
                <asp:Button ID="InsertNationButton" runat="server" Text="Insert" onclick="InsertNationButton_Click" ValidationGroup="InsertNationValidationGroup" />
            </asp:TableCell>
        </asp:TableRow>
    </asp:Table>
    
    <asp:ObjectDataSource ID="NationObjectDataSource" runat="server" DeleteMethod="DeleteNation" 
        InsertMethod="InsertNation" SelectMethod="GetAllNations"
        TypeName="RealEstateMarket.RealEstateServiceReference.RealEstateWebServiceSoapClient" 
        UpdateMethod="UpdateNation">
        <DeleteParameters>
            <asp:Parameter Name="id" Type="Int32" />
        </DeleteParameters>
        <InsertParameters>
            <asp:Parameter Name="name" Type="String" />
            <asp:Parameter Name="nationCode" Type="String" />
        </InsertParameters>
        <UpdateParameters>
            <asp:Parameter Name="id" Type="Int32" />
            <asp:Parameter Name="name" Type="String" />
            <asp:Parameter Name="nationCode" Type="String" />
        </UpdateParameters>
    </asp:ObjectDataSource>
</asp:Content>
