<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="NationAdmin.aspx.cs" Inherits="RealEstateMarket.Admin.Dashboard.NationAdmin" %>
<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
    <h4>
        Cập nhật thông tin các quốc gia
    </h4>
    <asp:Table runat="server" Height="119px" Width="154px">
        <asp:TableRow>
            <asp:TableCell>
                <asp:GridView 
                    runat="server" 
                    ID="dataTable"
                    DataSourceID="dataSource"
                    DataKeyNames="ID"
                    AllowPaging="True" 
                    AutoGenerateDeleteButton="True"
                    AutoGenerateEditButton="True" BackColor="White" BorderColor="#336666" 
                    BorderStyle="Double" BorderWidth="3px" CellPadding="4" GridLines="Horizontal">
                    <SelectedRowStyle ForeColor="White" Font-Bold="True" 
                           BackColor="#339966"></SelectedRowStyle>
                        <FooterStyle BackColor="White" ForeColor="#333333" />
                    <HeaderStyle BackColor="#336666" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#336666" ForeColor="White" HorizontalAlign="Center" />
                        <RowStyle ForeColor="#333333" BackColor="White"></RowStyle>
                    <SortedAscendingCellStyle BackColor="#F7F7F7" />
                    <SortedAscendingHeaderStyle BackColor="#487575" />
                    <SortedDescendingCellStyle BackColor="#E5E5E5" />
                    <SortedDescendingHeaderStyle BackColor="#275353" />
                </asp:GridView>
            </asp:TableCell>
            <asp:TableCell>
                <asp:Label ID="lblName" runat="server" Text="Nation's name:"></asp:Label>
                <asp:TextBox ID="textboxName" runat="server"></asp:TextBox>
                <br/>
                <asp:Label ID="lblNationCode" runat="server" Text="Nation Code:"></asp:Label>
                <asp:TextBox ID="textboxNationCode" runat="server"></asp:TextBox>
                <br />
                <asp:Button ID="Insert" runat="server" Text="Insert" onclick="Insert_Click" />
                <asp:Label ID="error" runat="server" Text="Label"></asp:Label>
            </asp:TableCell>
        </asp:TableRow>
    </asp:Table>
    <asp:ObjectDataSource ID="dataSource" runat="server" DeleteMethod="DeleteNation" 
        InsertMethod="InsertNation" SelectMethod="GetAllNations"
        TypeName="RealEstateMarket.RealEstateServiceReference.RealEstateWebServiceSoapClient" 
        UpdateMethod="UpdateNation">
        <DeleteParameters>
            <asp:Parameter Name="id" Type="Int32" />
        </DeleteParameters>
        <InsertParameters>
            <asp:Parameter Name="name" Type="String" />
            <asp:Parameter Name="nationCode" Type="String" />
        </InsertParameters>
        <UpdateParameters>
            <asp:Parameter Name="id" Type="Int32" />
            <asp:Parameter Name="name" Type="String" />
            <asp:Parameter Name="nationCode" Type="String" />
        </UpdateParameters>
    </asp:ObjectDataSource>
    

    
</asp:Content>
